name: PlayerControl
version: '${project.version}'
main: dev.mrviper111.playercontrol.PlayerControl
api-version: 1.16
authors: [ MrViper111 ]
description: A funky plugin

commands:
  controlplayer: {}
  closecontrollink: {}